export const CV = {
  data: {
    name: "Denesis",
    lastName: "Colmenarez",
    age:'27',
    city: "Toledo",
    email: "dcolmenarez1901@gmail.com",
    phone: "632990887",
    image: "https://i.imgur.com/MB2wQbm.png",
    gitHub: "https://github.com/Denesis",
    linkedin: "https://www.linkedin.com/in/denesis-colmenarez-0136a4184",
    aboutMe: [
      "Desarrolladora Fron-End | UX/UI",
      "Como ya habrás podido ver, me llamo Denesis Colmenarez. Soy desarrolladora Front-End en constante formación, que ha incursionando en el mundo tecnologico.",
      " Me considero una persona con una mente inquieta a la que le gusta aprender por sí misma, cada proyecto es un nuevo reto para aprender y crecer profesionalmente.",
      "Espero tener la oportunidad de aportar tanto mi experiencia como mi visión del diseño y la creatividad digital en tus proyectos.",
    ],
  },

  education: [
    {
      name: "Front End Developer",
      date: "2022",
      where: "Upgrade Hub | Madrid",
    },
    {
      name: "UX/UI Design",
      date: "2021",
      where: "Nuclio Digital School | Barcelona",
    },
    {
      name: "Marketing",
      date: "2019",
      where: "Universidad Jose Antonio Paez | Venezuela",
    },
  ],

  experience: [
    {
      name: "Agente de Seguros",
      date: "2020 Jun - Nov",
      where: "Ocaso Seguros y Reaseguros | Toledo",
      descripcion: [
        "Captación de clientes",
        "Conocimiento de productos",
        "Mantenimiento de cartera",
        "Telemarketing",
        "Asesoramiento personalizado",
        "Elaboración de presupuestos",
        "Atención al cliente",
        "Técnicas de venta",
      ],
    },
    {
      name: "Ejecutiva de Ventas",
      date: "2016 Ene - 2019 Abr",
      where: "Distribuciones Hanei Motors, C.A | Venezuela",
      descripcion: [
        "Captación de clientes",
        "Posicionamiento de empresa",
        "Visitas Face to Face",
        "Recepción de pedidos",
        "Telemarketing",
        "Cobranzas",
        "Asesoramiento personalizado",
        "Entrega de mercancía",
        "Gestión de incidencias",
        "Devoluciones",
        "Comercio mayorista",
        "Envío de albaranes",
      ],
    },
    {
      name: "Asistente de ventas",
      date: "2014 Abr-2015 Dic",
      where: "Representaciones Asiáticas, C.A | Venezuela",
      descripcion: [
        "Captación de clientes",
        "Recepción de pedidos",
        "Telemarketing",
        "Facturación",
        "Generación de albaranes",
        "Atención al cliente",
        "Asesoramiento personalizado",
        "Inventario y stock",
        "Gestión de incidencias",
        "Cuentas por cobrar",
        "Devoluciones",
        "Generación de listas de precios",
      ],
    },
    {
      name: "Recepcionista",
      date: "2013 Oct-2014 Mar",
      where: "Representaciones Asiáticas, C.A | Venezuela",
      descripcion: [
        "Recepción y emisión de llamadas",
        "Gestión de mensajería",
        "Listados de precios",
        "Archivo y gestión documental",
        "Atención al cliente",
        "Gestión de cuentas de correo",
        "Envío de facturas",
        "Gestión de agendas",
      ],
    },
  ],

  abilities: ["HMTL & CSS", "JavaScript", "TypeScript", "React", "Angular", "Figma", "Sketch", "GitHub"],
};
